/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 GuatemalanIsland.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/GuatemalanIsland.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={materials.Material} scale={4} />
      <mesh geometry={nodes.Roundcube.geometry} material={materials.Grass} position={[0, 0.547, 0]} />
      <mesh geometry={nodes.Roundcube001.geometry} material={materials.Water} position={[0, 0.547, 0]} />
      <group position={[-2.261, 1.585, 1.363]} rotation={[Math.PI, -1.149, Math.PI]} scale={0.275}>
        <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials['Material.005']} />
      </group>
      <group position={[-1.892, 1.332, 2.393]} scale={0.028}>
        <mesh geometry={nodes.Tree_1.geometry} material={materials['trunk color']} />
        <mesh geometry={nodes.Tree_2.geometry} material={materials['branch color.001']} />
        <mesh geometry={nodes.Tree_3.geometry} material={materials['branch color']} />
        <mesh geometry={nodes.Tree_4.geometry} material={materials['branch color.003']} />
      </group>
      <group position={[-1.892, 1.359, 0.986]} scale={0.022}>
        <mesh geometry={nodes.Tree001_1.geometry} material={materials['trunk color']} />
        <mesh geometry={nodes.Tree001_2.geometry} material={materials['branch color.001']} />
        <mesh geometry={nodes.Tree001_3.geometry} material={materials['branch color']} />
        <mesh geometry={nodes.Tree001_4.geometry} material={materials['branch color.003']} />
      </group>
      <group position={[2.074, 0.824, 1.059]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[3.004, 0.906, 1.22]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.393, 0.955, 0.669]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.031, 0.779, 0.46]} rotation={[Math.PI / 2, 0, 1.227]} scale={0.001}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[1.825, 0.906, 1.206]} rotation={[Math.PI / 2, 0, 1.227]} scale={0.001}>
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.138, 0.955, 1.373]} rotation={[Math.PI / 2, 0, 1.227]} scale={0.001}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.682, 0.824, 1.118]} rotation={[Math.PI / 2, 0, 0.436]} scale={0.001}>
        <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder008_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.395, 0.906, 1.146]} rotation={[Math.PI / 2, 0, 1.663]} scale={0.001}>
        <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder009_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.607, 0.955, 1.429]} rotation={[Math.PI / 2, 0, 1.663]} scale={0.001}>
        <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder010_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-2.203, 1.411, 2.393]} rotation={[0, 1.023, 0]} scale={0.019}>
        <mesh geometry={nodes.Tree002_1.geometry} material={materials['trunk color']} />
        <mesh geometry={nodes.Tree002_2.geometry} material={materials['branch color.001']} />
        <mesh geometry={nodes.Tree002_3.geometry} material={materials['branch color']} />
        <mesh geometry={nodes.Tree002_4.geometry} material={materials['branch color.003']} />
      </group>
      <group position={[-1.444, 1.287, 1.226]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Material.010']} />
      </group>
      <group position={[2.348, 0.955, 1.579]} rotation={[Math.PI / 2, 0, -0.636]} scale={0.001}>
        <mesh geometry={nodes.Cylinder012.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder012_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[1.932, 0.824, 1.626]} rotation={[Math.PI / 2, 0, 0.591]} scale={0.001}>
        <mesh geometry={nodes.Cylinder013.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder013_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.97, 1.046, -0.014]} rotation={[Math.PI / 2, 0, 0.889]} scale={0.001}>
        <mesh geometry={nodes.Cylinder014.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder014_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[3.358, 0.982, 0.679]} rotation={[Math.PI / 2, 0, 0.889]} scale={0.001}>
        <mesh geometry={nodes.Cylinder015.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder015_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[3.394, 1.097, -0.012]} rotation={[Math.PI / 2, 0, 0.889]} scale={0.001}>
        <mesh geometry={nodes.Cylinder016.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder016_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[3.338, 1.228, -0.359]} rotation={[Math.PI / 2, 0, 2.116]} scale={0.001}>
        <mesh geometry={nodes.Cylinder017.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder017_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.743, 1.111, -0.098]} rotation={[Math.PI / 2, 0, 2.116]} scale={0.001}>
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder018_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.799, 1.049, 0.195]} rotation={[Math.PI / 2, 0, 2.116]} scale={0.001}>
        <mesh geometry={nodes.Cylinder019.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder019_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[3.254, 0.96, 0.415]} rotation={[Math.PI / 2, 0, 1.325]} scale={0.001}>
        <mesh geometry={nodes.Cylinder020.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder020_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[3.084, 0.993, 0.242]} rotation={[Math.PI / 2, 0, 2.552]} scale={0.001}>
        <mesh geometry={nodes.Cylinder021.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder021_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[3.011, 1.04, 0.531]} rotation={[Math.PI / 2, 0, 2.552]} scale={0.001}>
        <mesh geometry={nodes.Cylinder022.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder022_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.776, 1.024, 0.441]} rotation={[Math.PI / 2, 0, 0.252]} scale={0.001}>
        <mesh geometry={nodes.Cylinder023.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder023_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.525, 0.926, 0.195]} rotation={[Math.PI / 2, 0, 1.48]} scale={0.001}>
        <mesh geometry={nodes.Cylinder024.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder024_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[2.932, 0.955, 0.836]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cylinder025.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder025_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-2.47, 1.379, 2.614]} rotation={[-Math.PI, 0.036, -Math.PI]} scale={0.028}>
        <mesh geometry={nodes.Tree003_1.geometry} material={materials['trunk color']} />
        <mesh geometry={nodes.Tree003_2.geometry} material={materials['branch color.001']} />
        <mesh geometry={nodes.Tree003_3.geometry} material={materials['branch color']} />
        <mesh geometry={nodes.Tree003_4.geometry} material={materials['branch color.003']} />
      </group>
      <group position={[-2.159, 1.419, 2.625]} rotation={[Math.PI, -0.987, Math.PI]} scale={0.019}>
        <mesh geometry={nodes.Tree004_1.geometry} material={materials['trunk color']} />
        <mesh geometry={nodes.Tree004_2.geometry} material={materials['branch color.001']} />
        <mesh geometry={nodes.Tree004_3.geometry} material={materials['branch color']} />
        <mesh geometry={nodes.Tree004_4.geometry} material={materials['branch color.003']} />
      </group>
      <group position={[-1.92, 1.343, 2.606]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cylinder026.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder026_1.geometry} material={materials['Material.010']} />
      </group>
      <group position={[-2.26, 1.387, 2.792]} rotation={[Math.PI / 2, 0, 1.207]} scale={0.001}>
        <mesh geometry={nodes.Cylinder027.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder027_1.geometry} material={materials['Material.010']} />
      </group>
      <group position={[2.567, 1.383, 0.75]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cylinder028.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder028_1.geometry} material={materials['Material.010']} />
      </group>
      <group position={[2.878, 1.357, 1.451]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cylinder029.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder029_1.geometry} material={materials['Material.010']} />
      </group>
      <group position={[2.494, 1.357, 1.754]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Cylinder030.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder030_1.geometry} material={materials['Material.010']} />
      </group>
      <group position={[2.295, 1.34, 0.184]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Cylinder031.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder031_1.geometry} material={materials['Material.010']} />
      </group>
      <mesh geometry={nodes.peire.geometry} material={materials['Material.011']} position={[1.5, 1.291, 1.664]} rotation={[Math.PI, -0.455, Math.PI]} scale={0.084} />
      <group position={[1.355, 1.811, -1.792]} rotation={[0, -0.771, 0]} scale={0.072}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['Glass_window&Door']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.Wall_03} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials.Wall_04} />
        <mesh geometry={nodes.Cube002_4.geometry} material={materials.Wall_05} />
        <mesh geometry={nodes.Cube002_5.geometry} material={materials['Material.012']} />
      </group>
      <group position={[2.054, 1.479, -2.374]} rotation={[Math.PI, -1.307, Math.PI]} scale={0.1}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Glass_window&Door']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.Wall_08} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials.Wall_05} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials.Wall_06} />
        <mesh geometry={nodes.Cube006_5.geometry} material={materials.Wall_07} />
      </group>
    </group>
  )
}

useGLTF.preload('/GuatemalanIsland.gltf')
